#!/bin/bash
#: Title       : register
#: Date        : 2011-10-09
#: Author      : "Ery Lee" <ery.lee@gmail.com> from nodehub.cn
#: Version     : 1.0 
#: Description : register a node

#script metadata
version=1.0
scriptname=${0##*/}
timestamp=`date +%s`
description="register a node"
date_of_creation=2011-10-08
usage="$scriptname [-v | -u User | -p Password] NodeName NodeLabel"
author="Ery Lee <ery.lee@gmail.com>"

usage() #@ DESCRIPTION: print usage information 
{       #@ USAGE: usage 
        #@ REQUIRES: variable defined: $scriptname 
  printf "%s - %s\n" "$scriptname" "$description" 
  printf "USAGE: %s\n" "$usage" 
} 
 
version() #@ DESCRIPTION: print version information 
{         #@ USAGE: version 
          #@ REQUIRES: variables defined: $scriptname, $author and $version 
  printf "%s version %s\n" "$scriptname" "$version" 
  printf "by %s, %d\n" "$author"  "${date_of_creation%%-*}" 
} 

## parse cli options, -v, -H, -u, -p, -w, -c
while getopts vhu:p:m: var 
do 
  case $var in 
    h) usage; exit ;; 
    v) version; exit ;; 
    u) user=$OPTARG ;;
    p) password=$OPTARG ;;
    m) master=$OPTARG ;;
  esac 
done 
shift $(( $OPTIND - 1 )) 

node_name=$1

node_label=$2

node_descr=`uname -a`

node_addrs=`ifconfig -a | grep "inet addr" | awk '{ print $2 }' | awk 'BEGIN { FS=":" } { print $2 }'`


if [ -z "$node_name"  ]; then
    usage
    exit -1
fi

if [ -z "$node_label"  ]; then
    usage
    exit -1
fi

result=`curl -s --data "login=$user&password=$password&node[name]=$node_name&node[label]=$node_label&node[addr]=\"$node_addrs\"&node[descr]=\"$node_descr\"" http://hub.nextim.cn:5000/nodes`

array=( $result )
i=0
len=${#array[*]}
while [ $i -lt $len ]; do
    if [ "status:" = "${array[$i]}" ]; then
        ok=${array[$i+1]}
    elif [ "name:" = "${array[$i]}" ]; then
        node_name=${array[$i+1]}
    elif [ "apikey:" = "${array[$i]}" ]; then
        node_apikey=${array[$i+1]}
    fi 
    let i++
done

if [ "$ok" = "ok" ]; then
    {
        echo "smarta {"
        echo "	name $node_name"
        echo "	server nodehub.cn"
        echo "	apikey $node_apikey"
    } > etc/smarta
    if [ -n "$master" ]; then
        echo "	master $master" >> etc/smarta
    fi
    echo "}" >> etc/smarta
    echo "node name: $node_name" 
    echo "node apikey: $node_apikey"
    echo "register successfully!"
else
    echo "register failure:"
    echo $result
fi


