#!/bin/bash
#: Title       : check_mysql_innodb
#: Date        : 2011-10-08
#: Author      : "Ery Lee" <ery.lee@gmail.com> from nodehub.cn
#: Version     : 1.0 
#: Description : check mysql innodb

version=1.0
scriptname=${0##*/}
timestamp=`date +%s`
description="check mysql innodb"
date_of_creation=2011-10-08
usage="$scriptname [-v | -h Host | -u User | -p Password | -w Warning | -c Critical]"
author="Ery Lee <ery.lee@gmail.com>"

usage() #@ DESCRIPTION: print usage information 
{       #@ USAGE: usage 
        #@ REQUIRES: variable defined: $scriptname 
  printf "%s - %s\n" "$scriptname" "$description" 
  printf "USAGE: %s\n" "$usage" 
} 
 
version() #@ DESCRIPTION: print version information 
{         #@ USAGE: version 
          #@ REQUIRES: variables defined: $scriptname, $author and $version 
  printf "%s version %s\n" "$scriptname" "$version" 
  printf "by %s, %d\n" "$author"  "${date_of_creation%%-*}" 
} 

## parse cli options, -v, -H, -u, -p, -w, -c
while getopts vhH:u:p:w:c: var 
do 
  case $var in 
    h) usage; exit ;; 
    v) version; exit ;; 
    H) host_opt="-h$OPTARG" ;; 
    u) user_opt="-u$OPTARG" ;;
    p) pass_opt="-p$OPTARG" ;;
    w) warn=$OPTARG ;;
    c) critical=$OPTARG ;;
  esac 
done 
shift $(( $OPTIND - 1 )) 

array=(`mysql $host_opt $user_opt $pass_opt -s -e "show global variables where Variable_name = 'innodb_buffer_pool_size';" | awk "{print $1 $2}"`)

for (( i=0; i<${#array[*]}; ++i )) 
do
    if [ "innodb_buffer_pool_size" = "${array[$i]}" ]; then
        buffer_pool_size=${array[$i+1]}
    fi
done
# retrive innodb variables
out2=`mysql $host_opt $user_opt $pass_opt -s -e "show global variables like 'innodb_%';" | awk "{print $1 $2}" `

# retrieve innodb status
out3=`mysql  $host_opt $user_opt $pass_opt -s -e "show global status like 'Innodb_%'" | awk  "{print $1 $2}" `
echo "OK - MySQL Innodb缓存池大小: $buffer_pool_size"
echo ""
echo "$out2"
#echo "$out3"
