#!/bin/bash
#: Title       : check_mysql_slow
#: Date        : 2011-10-02
#: Author      : "Ery Lee" <ery.lee@gmail.com> from nodehub.cn
#: Version     : 1.0 
#: Description : check mysql slow query

#script metadata
version=1.0
scriptname=${0##*/}
timestamp=`date +%s`
description="check mysql slow query"
date_of_creation=2011-10-08
usage="$scriptname [-v | -h Host | -u User | -p Password | -w Warning | -c Critical]"
author="Ery Lee <ery.lee@gmail.com>"
home=${HOME}/.smarta
mkdir -p $home
tmpfile="$home/.${scriptname}"

usage() #@ DESCRIPTION: print usage information 
{       #@ USAGE: usage 
        #@ REQUIRES: variable defined: $scriptname 
  printf "%s - %s\n" "$scriptname" "$description" 
  printf "USAGE: %s\n" "$usage" 
} 
 
version() #@ DESCRIPTION: print version information 
{         #@ USAGE: version 
          #@ REQUIRES: variables defined: $scriptname, $author and $version 
  printf "%s version %s\n" "$scriptname" "$version" 
  printf "by %s, %d\n" "$author"  "${date_of_creation%%-*}" 
} 

## parse cli options, -v, -H, -u, -p, -w, -c
while getopts vhH:u:p:w:c: var 
do 
  case $var in 
    h) usage; exit ;; 
    v) version; exit ;; 
    H) host_opt="-h$OPTARG" ;; 
    u) user_opt="-u$OPTARG" ;;
    p) pass_opt="-p$OPTARG" ;;
    w) warn=$OPTARG ;;
    c) critical=$OPTARG ;;
  esac 
done 
shift $(( $OPTIND - 1 )) 

array=(`mysql $host_opt $user_opt $pass_opt -s -e "show global status like 'Slow_%'" | awk "{print $1 $2}"`)

i=0
while [ $i -lt ${#array[*]} ]; do
    if [ "Slow_launch_threads" = "${array[$i]}" ]; then
        slow_launch_threads=${array[$i+1]}
    elif [ "Slow_queries" = "${array[$i]}" ]; then
        slow_queries=${array[$i+1]}
    fi 
    let i++
done

if [ -f $tmpfile ]; then
    array=(`cat $tmpfile | awk "{print $1 $2}"`)
    i=0
    while [ $i -lt ${#array[*]} ]; do
        if [ "Timestamp" = "${array[$i]}" ]; then
            old_timestamp=${array[$i+1]}
        elif [ "Slow_queries" = "${array[$i]}" ]; then
            old_slow_queries=${array[$i+1]}
        fi 
        let i++
    done
fi

{
echo "Timestamp $timestamp"
echo "Slow_queries $slow_queries"
} > $tmpfile

if [ $old_timestamp ]; then
    tdiff=$(($timestamp-$old_timestamp))
fi

if [ $old_slow_queries ]; then
    diff=$((slow_queries-$old_slow_queries))
    slow_queries_rate=$(($diff/$tdiff))
fi

slowvar=`mysql $host_opt $user_opt $pass_opt -s -e "show global variables like '%slow%'" | awk "{print $1 $2}" `

if [ $slow_queries_rate ]; then
    if [ -n "$critical" ] && eval "test $critical"
    then
        status="CRITICAL"
    elif [ -n "$warn" ] && eval "test $warn"
    then
        status="WARNING"
    else
        status="OK"
    fi
    echo "$status - MYSQL 慢查询总数: $slow_queries, 每秒慢查询: $slow_queries_rate" 
else
    echo "OK - MYSQL  慢查询总数: $slow_queries"
fi

echo ""
echo "$slowvar"

