#!/bin/bash
#: Title       : check_mysql_key
#: Date        : 2011-10-08
#: Author      : "Ery Lee" <ery.lee@gmail.com> from nodehub.cn
#: Version     : 1.0 
#: Description : check mysql key

version=1.0
scriptname=${0##*/}
timestamp=`date +%s`
description="check mysql key"
date_of_creation=2011-10-08
usage="$scriptname [-v | -h Host | -u User | -p Password | -w Warning | -c Critical]"
author="Ery Lee <ery.lee@gmail.com>"

usage() #@ DESCRIPTION: print usage information 
{       #@ USAGE: usage 
        #@ REQUIRES: variable defined: $scriptname 
  printf "%s - %s\n" "$scriptname" "$description" 
  printf "USAGE: %s\n" "$usage" 
} 
 
version() #@ DESCRIPTION: print version information 
{         #@ USAGE: version 
          #@ REQUIRES: variables defined: $scriptname, $author and $version 
  printf "%s version %s\n" "$scriptname" "$version" 
  printf "by %s, %d\n" "$author"  "${date_of_creation%%-*}" 
} 

## parse cli options, -v, -H, -u, -p, -w, -c
while getopts vhH:u:p:w:c: var 
do 
  case $var in 
    h) usage; exit ;; 
    v) version; exit ;; 
    H) host_opt="-h$OPTARG" ;; 
    u) user_opt="-u$OPTARG" ;;
    p) pass_opt="-p$OPTARG" ;;
    w) warn=$OPTARG ;;
    c) critical=$OPTARG ;;
  esac 
done 
shift $(( $OPTIND - 1 )) 

Out1=`mysql $host_opt $user_opt $pass_opt -s -e "show global variables where Variable_name in ('key_buffer_size', 'key_cache_age_threshold', 'key_cache_block_size', 'key_cache_division_limit');" | awk "{print $1 $2}" `

array=( $Out1 )

for (( i=0; i<${#array[*]}; ++i )) 
do
    if [ "key_buffer_size" = "${array[$i]}" ]; then
        key_buffer_size=${array[$i+1]}
    fi
done

Out2=`mysql $host_opt $user_opt $pass_opt -s -e "show global status where Variable_name in ('Key_read_requests', 'Key_reads', 'Key_write_requests', 'Key_writes', 'Key_blocks_unused', 'Key_blocks_used', 'Key_blocks_not_flushed');" | awk "{print $1 $2}" `

echo "OK - MySQL Key缓存大小: $key_buffer_size"
echo ""
echo "$Out1"
echo "$Out2"
