#!/bin/bash

# check mysql variables by "show global variables"
# author: ery.lee@gmail.com from nodehub.cn
source "./mysql_setting"

Out=`mysql -u$USER -p$PASS  -s -e "show global variables" | awk "{print $1 $2}" `
echo "OK - mysql variables"
echo ""
echo "$Out"
