#!/bin/bash
#: Title       : check_mysql_locks
#: Date        : 2011-10-08
#: Author      : "Ery Lee" <ery.lee@gmail.com> from nodehub.cn
#: Version     : 1.0 
#: Description : check mysql locks

version=1.0
scriptname=${0##*/}
timestamp=`date +%s`
description="check mysql locks"
date_of_creation=2011-10-08
usage="$scriptname [-v | -h Host | -u User | -p Password | -w Warning | -c Critical]"
author="Ery Lee <ery.lee@gmail.com>"

usage() #@ DESCRIPTION: print usage information 
{       #@ USAGE: usage 
        #@ REQUIRES: variable defined: $scriptname 
  printf "%s - %s\n" "$scriptname" "$description" 
  printf "USAGE: %s\n" "$usage" 
} 
 
version() #@ DESCRIPTION: print version information 
{         #@ USAGE: version 
          #@ REQUIRES: variables defined: $scriptname, $author and $version 
  printf "%s version %s\n" "$scriptname" "$version" 
  printf "by %s, %d\n" "$author"  "${date_of_creation%%-*}" 
} 

## parse cli options, -v, -H, -u, -p, -w, -c
while getopts vhH:u:p:w:c: var 
do 
  case $var in 
    h) usage; exit ;; 
    v) version; exit ;; 
    H) host_opt="-h$OPTARG" ;; 
    u) user_opt="-u$OPTARG" ;;
    p) pass_opt="-p$OPTARG" ;;
    w) warn=$OPTARG ;;
    c) critical=$OPTARG ;;
  esac 
done 
shift $(( $OPTIND - 1 )) 

# retrieve status
array=(`mysql $host_opt $user_opt $pass_opt -s -e "show status where Variable_name in ('Table_locks_immediate', 'Table_locks_waited');" | awk "{print $1 $2}" `)

for (( i=0; i<${#array[*]}; ++i )) 
do
    if [ "Table_locks_immediate" = "${array[$i]}" ]; then
        locks_immediate=${array[$i+1]}
    elif [ "Table_locks_waited" = "${array[$i]}" ]; then
        locks_waited=${array[$i+1]}
    fi
done

echo "OK - MySQL immediate locks: $locks_immediate, waited locks: $locks_waited"
echo ""
