#!/bin/bash
#: Title       : check_mysql_handler
#: Date        : 2011-10-08
#: Author      : "Ery Lee" <ery.lee@gmail.com> from nodehub.cn
#: Version     : 1.0 
#: Description : check mysql handlers

version=1.0
scriptname=${0##*/}
timestamp=`date +%s`
description="check mysql handlers"
date_of_creation=2011-10-08
usage="$scriptname [-v | -h Host | -u User | -p Password | -w Warning | -c Critical]"
author="Ery Lee <ery.lee@gmail.com>"

query="show global status where Variable_name like  'Handler_%';"

usage() #@ DESCRIPTION: print usage information 
{       #@ USAGE: usage 
        #@ REQUIRES: variable defined: $scriptname 
  printf "%s - %s\n" "$scriptname" "$description" 
  printf "USAGE: %s\n" "$usage" 
} 
 
version() #@ DESCRIPTION: print version information 
{         #@ USAGE: version 
          #@ REQUIRES: variables defined: $scriptname, $author and $version 
  printf "%s version %s\n" "$scriptname" "$version" 
  printf "by %s, %d\n" "$author"  "${date_of_creation%%-*}" 
} 

## parse cli options, -v, -H, -u, -p, -w, -c
while getopts vhH:u:p:w:c: var 
do 
  case $var in 
    h) usage; exit ;; 
    v) version; exit ;; 
    H) host_opt="-h$OPTARG" ;; 
    u) user_opt="-u$OPTARG" ;;
    p) pass_opt="-p$OPTARG" ;;
    w) warn=$OPTARG ;;
    c) critical=$OPTARG ;;
  esac 
done 
shift $(( $OPTIND - 1 )) 

array=(`mysql $host_opt $user_opt $pass_opt -s -e "$query" | awk "{print $1 $2}"`)

for (( i=0; i<${#array[*]}; ++i )) 
do
    if [ "Handler_commit" = "${array[$i]}" ]; then
        handler_commit=${array[$i+1]}
    elif [ "Handler_delete" = "${array[$i]}" ]; then
        handler_delete=${array[$i+1]}
    elif [ "Handler_update" = "${array[$i]}" ]; then
        handler_update=${array[$i+1]}
    elif [ "Handler_write" = "${array[$i]}" ]; then
        handler_write=${array[$i+1]}
    fi
done

if [ -n "$critical" ] && eval "test $critical"
then
    status="CRITICAL"
elif [ -n "$warn" ] && eval "test $warn"
then
    status="WARNING"
else
    status="OK"
fi

echo "$status - mysql table handler, handler_commit: $handler_commit, handler_delete: $handler_delete, handler_update: $handler_update, handler_write: $handler_write"
echo ""
